In [3]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
arr=np.array([2,4,6,8])
print(arr)
print(type(arr))

[2 4 6 8]
<class 'numpy.ndarray'>


In [5]:
print(np.__version__)

2.4.1


In [6]:
arr=np.array((1,2,3,4,5,6))
print(arr)

[1 2 3 4 5 6]


In [7]:
print(arr)

[1 2 3 4 5 6]


In [8]:
#O-dimensional array
arr=np.array(23)
print(arr)
print("Number of dimensions: ",arr.ndim)
print(arr.shape)

23
Number of dimensions:  0
()


In [9]:
#1-dimensional array
arr=np.array([1,2,3,4,5])
print(arr)
print("number of dimensions: ",arr.ndim)
print(arr.shape)

[1 2 3 4 5]
number of dimensions:  1
(5,)


In [11]:
#2-dimensional array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("Number of dimensions: ",arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
Number of dimensions:  2
(2, 3)


In [126]:
#define dimensionality while creating ndarray
arr=np.array(1,ndmin=5)
print(arr)
print("number of dimensions: ",arr.ndim)
arr.shape

[[[[[1]]]]]
number of dimensions:  5


(1, 1, 1, 1, 1)

In [127]:
#getting ranged values(start,stop,step)
d1=np.arange(1,10,2)
print(d1)

[1 3 5 7 9]


In [128]:
#getting values in between range(start,stop,how many values)
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [129]:
#getting logarithmic values in between range(starting power,ending power,count)
arr=np.logspace(1,3,10)
print(arr)

[  10.           16.68100537   27.82559402   46.41588834   77.42636827
  129.1549665   215.443469    359.38136638  599.48425032 1000.        ]


In [130]:
#creating 0's array
arr=np.zeros([2,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [131]:
#creating 1's array
arr=np.ones([2,4],dtype=int)
print(arr)

[[1 1 1 1]
 [1 1 1 1]]


In [13]:
#creating custom numbers array
arr=np.full([2,6],7,dtype=int)
print(arr)

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [133]:
#creating 1d array with specified count and value
arr=np.full(10,2)
print(arr)

[2 2 2 2 2 2 2 2 2 2]


In [134]:
#empty array
arr=np.empty([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [135]:
#10 Random numbers between 0-1
arr=np.random.rand(10)
arr

array([0.21484248, 0.59345267, 0.51683163, 0.69932278, 0.83087483,
       0.14219409, 0.28831426, 0.97073613, 0.68357371, 0.23754666])

In [136]:
#random float numbers in rows and columns between 0 and 1
arr=np.random.rand(2,3)
arr

array([[0.30291452, 0.05687902, 0.4726363 ],
       [0.37423765, 0.41572491, 0.27104253]])

In [137]:
#random integer numbers 
arr=np.random.randint(10,100)
arr

18

In [138]:
#random number in rows & columns
arr=np.random.randint(10,100,size=(2,3))
arr

array([[96, 50, 63],
       [58, 94, 59]], dtype=int32)

In [139]:
arr=np.array([1,2,3.1])
arr

array([1. , 2. , 3.1])

In [140]:
#tpecasting
arr1=arr.astype(np.int64)
arr1

array([1, 2, 3])

In [141]:
arr=np.array([3.1,5.4125,54.91])
print(arr)
arr1=arr.astype(np.int64)
print(arr1)
arr1.itemsize

[ 3.1     5.4125 54.91  ]
[ 3  5 54]


8

In [142]:
arr.size

3

In [143]:
#reshape
arr=np.array([1,2,3,4,5,6])
reshape=arr.reshape(2,3)
print(reshape)
reshape2=reshape.reshape(3,2)
reshape2

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [144]:
#ravel
ravel=reshape2.ravel()
ravel
ravel[0]=20
print(ravel)
print(reshape2)

[20  2  3  4  5  6]
[[20  2]
 [ 3  4]
 [ 5  6]]


In [145]:
#flatten
flatten=reshape2.flatten()
flatten
flatten[0]=30
print(flatten)
print(reshape2)

[30  2  3  4  5  6]
[[20  2]
 [ 3  4]
 [ 5  6]]


In [146]:
retail_sales=np.full([30,5],8)
#print(retail_sales)
retail_sales[4]=-1
print(retail_sales)
print(retail_sales.shape)

[[ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [-1 -1 -1 -1 -1]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  8]]
(30, 5)


In [147]:
d1=np.array([1,2,3,4,5])
d2=np.array([6,7,8,9,1])
#addition
print(d1+d2)
print(d1-d2)
print(d1*d2)
print(d1/d2)
print(d1%d2)
print(d2//d1)
print(d1**2)


[ 7  9 11 13  6]
[-5 -5 -5 -5  4]
[ 6 14 24 36  5]
[0.16666667 0.28571429 0.375      0.44444444 5.        ]
[1 2 3 4 0]
[6 3 2 2 0]
[ 1  4  9 16 25]


In [148]:
print(np.sqrt(d1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [149]:
print(np.exp(d1))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [150]:
angles=np.array([0,np.pi/2,np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


Slicing

In [151]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[0])

1


In [152]:
print(arr[-1])

8


In [153]:
print(arr[-1:-4:-1])

[8 7 6]


In [154]:
print(arr[:])

[1 2 3 4 5 6 7 8]


In [15]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [16]:
print(arr[0:4])

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [157]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [158]:
ind=[0,2]
print(np.take(arr,ind))

[1 3]


In [159]:
for x in np.nditer(arr):
    print(x,end=" ")

1 2 3 4 5 6 7 8 9 10 

In [160]:
for x in np.ndenumerate(arr):
    print(x,end=" ")

((0,), np.int64(1)) ((1,), np.int64(2)) ((2,), np.int64(3)) ((3,), np.int64(4)) ((4,), np.int64(5)) ((5,), np.int64(6)) ((6,), np.int64(7)) ((7,), np.int64(8)) ((8,), np.int64(9)) ((9,), np.int64(10)) 

In [161]:
view=arr[1:3]
print(view)
view[0]=32
print(view)
print(arr)


[2 3]
[32  3]
[ 1 32  3  4  5  6  7  8  9 10]


In [162]:
copy=arr[:3].copy()
print(copy)
copy[0]=56
print(copy)
print(arr)

[ 1 32  3]
[56 32  3]
[ 1 32  3  4  5  6  7  8  9 10]


In [163]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
com=np.concatenate((arr1,arr2))
print(com)

[ 1  2  3  4  5  6  7  8  9 10]


In [164]:
d1=np.array([[1,2,3],[4,5,6]])
d2=np.array([[7,8,9],[10,11,12]])
print(np.vstack((d1,d2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [165]:
print(np.hstack((d1,d2)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [166]:
print(np.stack((d1,d2),axis=0))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [167]:
print(np.stack((d1,d2),axis=1))

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [168]:
print(np.split(d1,2))

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [169]:
print(np.repeat(d1,2))

[1 1 2 2 3 3 4 4 5 5 6 6]


In [170]:
print(np.tile(d1,2))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


Aggregate functions

In [171]:
arr=np.array([1,2,3,4,5])
print(np.sum(arr))

15


In [172]:
print(np.mean(arr))

3.0


In [173]:
print(np.median(arr))

3.0


In [174]:
print(np.std(arr))

1.4142135623730951


In [175]:
print(np.var(arr))

2.0


In [176]:
print(np.min(arr))

1


In [178]:
print(np.max(arr))

5


In [179]:
print(np.cumsum(arr))

[ 1  3  6 10 15]


In [180]:
print(np.cumprod(arr))

[  1   2   6  24 120]


In [181]:
print(np.where(arr>2,"True","False"))

['False' 'False' 'True' 'True' 'True']


In [182]:
print(np.argwhere(arr>2))

[[2]
 [3]
 [4]]


In [184]:
print(arr1)
print(np.logical_and(arr1>2,arr1<4))

[1 2 3 4 5]
[False False  True False False]


In [ ]:
mask=np.logical_or(arr1>2,arr1<4)
print(arr[mask])

[1 2 3 4 5]


In [187]:
mask=np.logical_and(arr1>2,arr1<4)
print(arr[mask])

[3]


In [188]:
arr=np.array([0,1,0,2,0,3])
print(np.nonzero(arr))

(array([1, 3, 5]),)


In [190]:
arr=np.array([1,2,np.inf,3,np.nan,4])
print(arr)

[ 1.  2. inf  3. nan  4.]


In [191]:
print(np.isnan(arr))

[False False False False  True False]


In [192]:
print(np.isinf(arr))

[False False  True False False False]


In [194]:
print(np.logical_or(np.isnan(arr),np.isinf(arr)))

[False False  True False  True False]


In [195]:
print(np.nan_to_num(arr))

[1.00000000e+000 2.00000000e+000 1.79769313e+308 3.00000000e+000
 0.00000000e+000 4.00000000e+000]


In [17]:
print(np.random.choice([1,2,3,4,5]))

4
